{{- if eq .Values.mode "deployment" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "locust.fullname" . }}
  labels:
    {{- include "locust.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "locust.selectorLabels" . | nindent 4 }}
{{- end }}
